#!/bin/sh

if [ $# -ne 0 -o ! -r Makefile ]; then
  ./configure \
    --without-mp3 \
    CC=gcc-4 \
    CPPFLAGS=-I/usr/local/include \
    LDFLAGS="-static -L/usr/local/lib" \
    $*
fi

make -s all pdf

dir="$(basename $(pwd))"
rm -rf $dir $dir.zip
mkdir -p $dir

for f in ChangeLog LICENSE.GPL README README.win32; do
  cp -p $f $dir/$f.txt
  unix2dos $dir/$f.txt
done

binaries=$(for f in `cygcheck src/sox /usr/bin/wget|dos2unix`
    do cygpath -u $f; done|sort|uniq|grep -v ^/cygdrive/)

cp -p \
  $binaries \
  sox.pdf \
  soxformat.pdf \
  soxi.pdf \
  libsox.pdf \
  scripts/batch-example.bat \
  $dir

unix2dos $dir/batch-example.bat

cp -p /etc/wgetrc $dir/wget.ini

zip -r $dir.zip $dir
rm -rf $dir
