#!/bin/sh
#
# This script will automates the steps used to producing a static win32
# package of SoX.
#
# It is used on a Fedora box with mingw cross compiler and wine to 
# test.  It can be used as a reference for command lines under MSYS.
#
# It will optionally package up VC++ version of wget if found in 
# ../wget-1.11.4.
#
# Various notes:
#
# Script makes use of "-static" option to tell compiler to prefer static
# external libraries so that we do not need to distribute DLL's. 
#
# Libtool will get confused with this flag for external libraries 
# that have a libtool lib*.la file and support shared libraries as 
# well as static libraries (but usually only if that library 
# further depends on other external libraries with lib*.la files). 
# Libtool may ignore -static option or it may link first external
# library as static but other dependent libraries as shared (usually
# because it follows $dependency_libs and that ignores -static option).
#
# Work arounds include to only install static libraries, delete the lib*.la 
# file, or edit the lib*.la file and set dlnames and library_names variables 
# to empty string ("").
#
# The following command lines were used to generate the static external
# libraries SoX ships with.
#
# mingw32-gcc refuses to find static version of libltdl when
# using "-static" flag.  So I compile and install only static
# version of libltdl to help compiler out (means I can use
# a packaged version).
# cd libtool-1.5.26
# mingw32-configure --disable-shared --enable-static;mingw32-make;sudu mingw32-make install
#
#
# libpng.la will have libtool issue because depends on libz
# which has a libz.la file.  Must edit libpng.la to
# prevent needing to distribute zlib1.dll.
# cd libpng-1.2.41
# mingw32-configure --disable-shared --enable-static;mingw32-make;sudu mingw32-make install
#
# MINGW work around: had to comment out "cli" from SUBDIR.
# cd ../wavpack-4.60.1
# mingw32-configure --disable-shared --enable-static;mingw32-make;sudo mingw32-make install
#
# MINGW fixes for FLAC: Needed to edit include/share/alloc.h and remove
# !defined __MINGW32__ check so that stdint.h is included.
# Edited Makefile and removed "examples" from SUBDIRS.
# cd ../flac-1.2.1
# mingw32-configure --disable-shared --enable-static;mingw32-make;sudo mingw32-make install
#
# cd ../libogg-1.1.4
# mingw32-configure --disable-shared --enable-static;mingw32-make;sudo mingw32-make install
#
# cd ../libvorbis-1.2.3
# mingw32-configure --disable-shared --enable-static;mingw-32-make;sudo mingw32-make install
#
# Compile libsndfile after FLAC and ogg vorbis so that it will include
# support for that.
# MINGW work around: Can either add -lwsock32 to end of *_LDADD for any 
# failed program links or modify top leve Makefile and remove
# "programs", "examples", "regtests", and "tests" from SUBDIRS.
# cd ../libsndfile-1.0.20
# mingw32-configure --disable-shared --enable-static;mingw32-make;sudo mingw32-make install
#
# To get MP3 header files used to enable MP3 support (no libraries used):
#
# cd ../lame-398-2
# mingw32-configure --enable-shared --disable-static;mingw32-make;sudo mingw32-make install
#
# cd ../libid3tag-0.15.1b
# mingw32-configure --enable-shared --disable-static;mingw32-make;sudo mingw32-make install
#
# MINGW work around: Edit Makefile and remove -fforce-mem from CFLAGS
# cd ../libmad-0.15.1b
# mingw32-configure --enable-shared --disable-static;mingw32-make;sudo mingw32-make install
#
# To get AMR header files used to eanble AMR support (no libraries used):
#
# cd ../opencore-amr-0.1.2
# mingw32-configure --enable-shared --disable-static;mingw32-make;sudo mingw32-make install

[ ! -x configure ] && autoreconf -i

# Some versions of autoconf (2.63?) seem to get easily confused about
# CPP variable. If you see warning messages about header files
# rejected by preprocessor then its most likely from that.
# Force the value of CPP=cpp works around that bug.
# static versions of libsndfile do not advertise when they have
# FLAC or ogg vorbis support.  Need to force the link ourselves.
if [ $# -ne 0 -o ! -r Makefile ]; then
  mingw32-configure \
    --disable-shared \
    --with-libltdl \
    --enable-dl-lame --enable-dl-mad --enable-dl-amrnb --enable-dl-amrwb \
    LDFLAGS="-static" \
    SNDFILE_LIBS="-lsndfile -lFLAC -lwsock32 -lvorbisenc -lvorbisfile -lvorbis -logg" \
    $*
fi

# Reduce total size of sox.exe by over half.
make -s all pdf txt || exit 1

i686-pc-mingw32-strip src/sox.exe

dir=sox-`grep Version: sox.pc | cut -d ' ' -f 2`
rm -rf $dir $dir-win32.zip
mkdir -p $dir

for f in ChangeLog LICENSE.GPL README README.win32; do
  cp -p $f $dir/$f.txt
  unix2dos $dir/$f.txt
done

binaries=src/sox.exe
# If you do not edit libpng.la to comment out shared libraries
# then you'll need to distribute zlib1.dll.
#binaries="$binaries /usr/i686-pc-mingw32/sys-root/mingw/bin/zlib1.dll"

binaries="$binaries /usr/i686-pc-mingw32/sys-root/mingw/bin/libgomp-1.dll"
binaries="$binaries /usr/i686-pc-mingw32/sys-root/mingw/bin/pthreadGC2.dll"

cp -p \
  $binaries \
  sox.pdf \
  soxformat.pdf \
  soxi.pdf \
  libsox.pdf \
  scripts/batch-example.bat \
  $dir

unix2dos $dir/batch-example.bat

if test -r "../wget-1.11.4/wget.exe"; then
  cp ../wget-1.11.4/wget.exe $dir
  cp ../wget-1.11.4/wget.ini $dir
fi

zip -r $dir-win32.zip $dir
rm -rf $dir
