.TH play 1 "December 11, 2001"
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
play \- play any sound file to audio device
.P
rec  \- record audio to any sound file format
.SH SYNOPSIS
.B play
.I "[fopts] infile [effect]"
.P
.B rec
.I "[fopts] outfile [effect]"
.SH "DESCRIPTION"
This manual page briefly documents the
.B play and rec
commands.
.PP
.B play
and
.B rec
are programs that allow you to play and record different types of sound files 
from the command line.  They are front ends to the more general 
.B sox(1) 
package.  Normally, the play command will automatically detect the 
type and other parameters of the soundfile. If it can't do 
so, the parameters can be changed through options.
.SH OPTIONS
A summary of common options are included below.
For a complete description of options and their values, see 
the 
.B sox(1) 
man page.
.TP
.B \-c [channels], \-\-channels=[channels]
Define the number of channels in the file.
.TP
.B \-d [device], \-\-device=[device]
Specify a different device to play the sound file to.
.TP
.B \-f [format], \-\-format=[format]
Specify bit format of the sample. One of s, u, U, A, a, or g.
.TP
.B \-r [rate], \-\-rate=[rate]
Specify the sample rate of the audio data (samples per second).
.TP
.B \-s [size], \-\-size=[size]
Specify the width of each sample.  One of b, w, l, f, d, or D.
.TP
.B \-t [type], \-\-type=[type]
Specify audio file format to use.  Useful if it can not be 
automatically determined.
.TP
.B \-v [volume], \-\-volume=[volume]
Change the audio volume
.TP
.B \-x , \-\-xinu
Reverse the byte order of the sample (only works with 16 and 32-bit data).
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-\-version
Show version of play/rec.

.TP
Description of effects are described in the 
.B sox(1) 
man page.

.SH "SEE ALSO"

 sox(1)
 soxexam(1)

.SH AUTHOR
This manual page was written by Guenter Geiger <geiger@iem.mhsg.ac.at>,
for the Debian GNU/Linux system.  
.P
Updates by Anonymous.
