.de Sh
.br
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.TH SoX 1 "December 10, 1999"
.SH NAME
sox \- Sound eXchange : universal sound sample translator
.SH SYNOPSIS
.B sox \fIinfile outfile \fB
.br
.B sox \fIinfile outfile \fB[ \fIeffect\fR 
.B [ \fIeffect options ...\fB ] ]
.br
.B sox \fIinfile \fB-e \fIeffect\fR 
.B [ \fIeffect options ...\fB ]
.br
.B sox
[\fI general options \fB ]
[ \fIformat options \fB ]
\fIinfile\fB 
[ \fIformat options \fB ]
\fIoutfile\fB 
[ \fIeffect\fR [ \fIeffect options ...\fB ] ]
.P
\fIGeneral options:\fB
[ -e ]
[ -h ]
[ -p ]
[ -v \fIvolume\fB ]
[ -V ]
.P
\fIFormat options:\fB
[ \fB-t \fIfiletype\fB ]
[ -r \fIrate\fB ]
[ -s/-u/-U/-A/-a/-i/-g ]
[ -b/-w/-l/-f/-d/-D ]
[ -c \fIchannels\fB ]
[ -x ]
.P
\fIEffects:\fB
.br
	avg [ \fI-l\fB | \fI-r\fB ]
.br
	band \fB[ \fI-n \fB] \fIcenter \fB[ \fIwidth\fB ]
.br
	bandpass \fIfrequency bandwidth\fB
.br
	bandreject \fIfrequency bandwidth\fB
.br
 	check 
.br
	chorus \fIgain-in gain out delay decay speed depth
		-s\fB | \fI-t\fB [ \fIdelay decay speed depth -s\fB | \fI-t\fB ]
.br
	compand \fIattack1,decay1\fB[,\fIattack2,decay2\fB...]
             \fIin-dB1,out-dB1\fB[,\fIin-dB2,out-dB2\fB...]
             [\fIgain\fB] [\fIinitial-volume\fB]
.br
	copy
.br
	cut
.br
	deemph
.br
	echo \fIgain-in gain-out delay decay\fB [ \fIdelay decay ...\fB]
.br
	echos \fIgain-in gain-out delay decay\fB [ \fIdelay decay ...\fB]
.br
	filter \fB[ \fIlow\fB ]\fI-\fB[ \fIhigh\fB ] [ \fIwindow-len\fB [ \fIbeta\fB ]]
.br
	flanger \fIgain-in gain-out delay decay speed -s\fB | \fI-t\fB
.br
	highp \fIcenter\fB
.br
	highpass \fIfrequency\fB
.br
	lowp \fIcenter\fB
.br
	lowpass \fIfrequency\fB
.br
	map
.br
	mask
.br
	pan \fIdirection\fB
.br
	phaser \fIgain-in gain-out delay decay speed -s\fB | \fI-t\fB
.br
	pick
.br
	polyphase [ \fI-w \fR< \fInut\fR / \fIham\fR > ] 
               [ \fI -width \fR< \fI long \fR / \fIshort \fR / \fI# \fR> ] 
               [ \fI-cutoff # \fR ]
.br
	\fBrate 
.br
	resample
.br
	reverb \fIgain-out reverb-time delay\fB [ \fIdelay ... \fB]
.br
	reverse
.br
	speed \ffactor\f
.br
	split
.br
	stat [ \fIdebug\fB | \fI-v\fB ]
.br
	swap [ \fI1 2 3 4\fB ]
.br
	vibro \fIspeed \fB[ \fIdepth\fB ]
.br
	vol \fIgain \fB[ \fItype\fB ]
.SH DESCRIPTION
.I SoX
is a command line program that can convert most popular audio files
to most other popular audio file formats.  It can optionally apply a
sound effect to the file during this translation.
.P
There are two types of audio files formats that
.I SoX
can work with.  The first are self-describing file formats.  These
contain a header that completely describe the characteristics of
the audio data that follows.
.P
The second type are headerless data, or sometimes called raw data.  A
user must pass enough information to
.I SoX
on the command line so that it knows what type of data it contains.
.P
Audio data can usually be totally described by four characteristics:
.TP 10
rate
The sample rate is in samples per second.  For example, CD sample rates are at 44100.
.TP 10 
data type
What format the data is stored in.  Most popular are 8-bit or 16-bit words.
.TP 10
data format
What encoding the data type uses.  Examples are u-law, ADPCM, or signed linear data.
.TP 10
channels
How many channels are contained in the audio data.  Mono and Stereo are the two most common.
.P
Please refer to the
.B soxexam(1)
manual page for a long description with examples on how to use sox with
various types of file formats.
.SH OPTIONS
The option syntax is a little grotty, but in essence:
.P
.br
	sox file.au file.voc 
.P
.br
translates a sound file in SUN Sparc .AU format 
into a SoundBlaster .VOC file, while
.P
.br
	sox -v 0.5 file.au -r 12000 file.voc rate
.P
.br
does the same format translation but also 
lowers the amplitude by 1/2 and changes
the sampling rate from 8000 hertz to 12000 hertz via
the
.B rate
\fIsound effect\fR loop.
.PP
Format options:
.PP
Format options effect the audio samples that they immediately percede.  If
they are placed before the input file name then they effect the input
data.  If they are placed before the output file name then they will
effect the output data.  By taking advantage of this, you can override
a input file's currupted header or produce an output file that is totally
different style then the input file.
.TP 10
\fB-t\fI filetype
gives the type of the sound sample file.
.TP 10
\fB-r \fIrate\fR
Give sample rate in Hertz of file.  To cause the output file to have
a different sample rate than the input file, include this option
with the appropriate rate value along with the output options.
If the input and output files have
different rates then a sample rate change effect must be ran.  If a
sample rate changing effect is not specified then a default one will be
used with its default parameters.
.TP 10
\fB-s/-u/-U/-A/-a/-i/-g\fR
The sample data format is signed linear (2's complement),
unsigned linear, U-law (logarithmic), A-law (logarithmic),
ADPCM, IMA_ADPCM, or GSM.
U-law and A-law are the U.S. and international
standards for logarithmic telephone sound compression.
ADPCM is form of sound compression that has a good
compromise between good sound quality and fast encoding/decoding
time.
IMA_ADPCM is also a form of adpcm compression, slightly simpler
and slightly lower fidelity than Microsoft's flavor of ADPCM.
IMA_ADPCM is also called DVI_ADPCM.
GSM is a standard used for telephone sound compression in
European countries and its gaining popularity because of its
quality.
.TP 10
\fB-b/-w/-l/-f/-d/-D\fR
The sample data type is in bytes, 16-bit words, 32-bit longwords,
32-bit floats, 64-bit double floats, or 80-bit IEEE floats.
Floats and double floats are in native machine format.
.TP 10
\fB-x\fR
The sample data is in XINU format; that is,
it comes from a machine with the opposite word order 
than yours and must
be swapped according to the word-size given above.
Only 16-bit and 32-bit integer data may be swapped.
Machine-format floating-point data is not portable.
IEEE floats are a fixed, portable format.
.TP 10
\fB-c \fIchannels\fR
The number of sound channels in the data file.
This may be 1, 2, or 4; for mono, stereo, or quad sound data.  To cause
the output file to have a different number of channels than the input
file, include this option with the approraite value with the output
file options.  
If the input and output file have a different number of channels then the
avg effect must be used.  If the avg effect is not specified on the 
command line it will be invoked with default parameters.
.PP
General options:
.TP 10
\fB-e\fR
When used after the input file (so that it applies to the output file)
it allows you to avoid giving an output filename and will not
produce an output file.  It will apply any specified effects
to the input file.  This is mainly useful with the
.B stat
effect but can be used with others.
.TP 10
\fB-h\fR
Print version number and usage information.
.TP 10
\fB-p\fR
Run in preview mode and run fast.  This will somewhat speed up
sox when the output format has a different number of channels and
a different rate than the input file.  The order that the effects 
are run in will be arranged for maximum speed and not quality.
.TP 10
\fB-v \fIvolume\fR
Change amplitude (floating point); 
less than 1.0 decreases, greater than 1.0 increases.
Note: we perceive volume logarithmically, not linearly.
Note: see the
.B stat
effect.
.TP 10
\fB-V\fR
Print a description of processing phases.
Useful for figuring out exactly how
.I sox
is mangling your sound samples.
.SH FILE TYPES
.I SoX
uses the file extension of the input and output file to determine what
type of file format to use.  This can be overriden by specifying the
"-t" option on the command line.
.P
The input and output files may be read from standard in and out.  This
is done by specifing '-' as the filename.
.P
File formats which have headers are checked, 
if that header doesn't seem right,
the program exits with an appropriate message.
.P
The following file formats are supported:
.PP
.TP 10
.B .8svx
Amiga 8SVX musical instrument description format.
.TP 10
.B .aiff
AIFF files used on Apple IIc/IIgs and SGI.
Note: the AIFF format supports only one SSND chunk.
It does not support multiple sound chunks, 
or the 8SVX musical instrument description format.
AIFF files are multimedia archives and
and can have multiple audio and picture chunks.
You may need a separate archiver to work with them.
.TP 10
.B .au
SUN Microsystems AU files.
There are apparently many types of .au files;
DEC has invented its own with a different magic number
and word order.  
The .au handler can read these files but will not write them.
Some .au files have valid AU headers and some do not.
The latter are probably original SUN u-law 8000 hz samples.
These can be dealt with using the 
.B .ul
format (see below).
.TP 10
.B .avr
Audio Visual Research
.br
The AVR format is produced by a number of commercial packages
on the Mac.
.TP 10
.B .cdr
CD-R
.br
CD-R files are used in mastering music Compact Disks.
The file format is, as you might expect, raw stereo
raw unsigned samples at 44khz.  But, there's
some blocking/padding oddity in the format, so it
needs its own handler.
.TP 10
.B .cvs
Continuously Variable Slope Delta modulation
.br
Used to compress speech audio for applications such as voice mail.
.TP 10
.B .dat      
Text Data files
.br
These files contain a textual representation of the
sample data.  There is one line at the beginning
that contains the sample rate.  Subsequent lines
contain two numeric data items: the time since
the beginning of the sample and the sample value.
Values are normalized so that the maximum and minimum
are 1.00 and -1.00.  This file format can be used to
create data files for external programs such as
FFT analyzers or graph routines.  SoX can also convert
a file in this format back into one of the other file
formats.
.TP 10
.B .gsm
GSM 06.10 Lossy Speech Compression
.br
A standard for compressing speech which is used in the
Global Standard for Mobil telecommunications (GSM).  Its good
for its purpose, shrinking audio data size, but it will introduce
lots of noise when a given sound sample is encoded and decoded
multiple times.  This format is used by some voice mail applications.
It is rather CPU intensive.
GSM in
.B sox
is optional and requires access to an external GSM library.  To see
if there is support for gsm run
.I sox -h
and look for it under the list of supported file formats.
.TP 10
.B .hcom
Macintosh HCOM files.
These are (apparently) Mac FSSD files with some variant
of Huffman compression.
The Macintosh has wacky file formats and this format
handler apparently doesn't handle all the ones it should.
Mac users will need your usual arsenal of file converters
to deal with an HCOM file under Unix or DOS.
.TP 10
.B .maud
An Amiga format
.br
An IFF-conform sound file type, registered by
MS MacroSystem Computer GmbH, published along
with the "Toccata" sound-card on the Amiga.
Allows 8bit linear, 16bit linear, A-Law, u-law
in mono and stereo.
.TP 10
.B ossdsp
OSS /dev/dsp device driver
.br
This is a pseudo-file type and can be optionally compiled into Sox.  Run
.B sox -h
to see if you have support for this file type.  When this driver is used
it allows you to open up the OSS /dev/dsp file and configure it to
use the same data type as passed in to
.B Sox.
It works for both playing and recording sound samples.  When playing sound
files it attempts to set up the OSS driver to use the same format as the
input file.  It is suggested to always override the output values to use
the highest quality samples your sound card can handle.  Example:
.I -t ossdsp -w -s /dev/dsp
.TP 10
.B .sf
IRCAM Sound Files.
.br
SoundFiles are used by academic music software 
such as the CSound package, and the MixView sound sample editor.
.TP 10
.B .smp
Turtle Beach SampleVision files.
.br
SMP files are for use with the PC-DOS package SampleVision by Turtle Beach
Softworks. This package is for communication to several MIDI samplers. All
sample rates are supported by the package, although not all are supported by
the samplers themselves. Currently loop points are ignored.
.TP 10
.B sunau
Sun /dev/audio device driver
.br
This is a pseudo-file type and can be optionally compiled into Sox.  Run
.B sox -h
to see if you have support for this file type.  When this driver is used
it allows you to open up a Sun /dev/audio file and configure it to
use the same data type as passed in to
.B Sox.
It works for both playing and recording sound samples.  When playing sound
files it attempts to set up the audio driver to use the same format as the
input file.  It is suggested to always override the output values to use
the highest quality samples your hardware can handle.  Example:
.I -t sunau -w -s /dev/audio
or
.I -t sunau -U -c 1 /dev/audio
for older sun equipment.
.TP 10
.B .txw
Yamaha TX-16W sampler.
.br
A file format from a Yamaha sampling keyboard which wrote IBM-PC
format 3.5" floppies.  Handles reading of files which do not have
the sample rate field set to one of the expected by looking at some
other bytes in the attack/loop length fields, and defaulting to
33kHz if the sample rate is still unknown.
.TP 10
.B .vms
More info to come.
.br
Used to compress speech audio for applications such as voice mail.
.TP 10
.B .voc
Sound Blaster VOC files.
.br
VOC files are multi-part and contain silence parts, looping, and
different sample rates for different chunks.
On input, the silence parts are filled out, loops are rejected,
and sample data with a new sample rate is rejected.
Silence with a different sample rate is generated appropriately.
On output, silence is not detected, nor are impossible sample rates.
.TP 10
.B .wav
Microsoft .WAV RIFF files.
.br
These appear to be very similar to IFF files,
but not the same.  
They are the native sound file format of Windows.
(Obviously, Windows was of such incredible importance
to the computer industry that it just had to have its own 
sound file format.)
Normally \fB.wav\fR files have all formatting information
in their headers, and so do not need any format options
specified for an input file. If any are, they will
override the file header, and you will be warned to this effect.
You had better know what you are doing! Output format
options will cause a format conversion, and the \fB.wav\fR
will written appropriately.
Sox currently can read PCM, ULAW, ALAW, MS ADPCM, and IMA (or DVI) ADPCM.
It can write all of these formats including
.B (NEW!)
the ADPCM encoding.
.TP 10
.B .wve
Psion 8-bit alaw
.br
These are 8-bit a-law 8khz sound files used on the
Psion palmtop portable computer.
.TP 10
.B .raw
Raw files (no header).
.br
The sample rate, size (byte, word, etc), 
and encoding (signed, unsigned, etc.)
of the sample file must be given.
The number of channels defaults to 1.
.TP 10
.B ".ub, .sb, .uw, .sw, .ul, .sl"
These are several suffices which serve as
a shorthand for raw files with a given size and encoding.
Thus, \fBub, sb, uw, sw, ul\fR and \fBsl\fR
correspond to "unsigned byte", "signed byte",
"unsigned word", "signed word", "ulaw" (byte), and "signed long".
The sample rate defaults to 8000 hz if not explicitly set,
and the number of channels (as always) defaults to 1.
There are lots of Sparc samples floating around in u-law format
with no header and fixed at a sample rate of 8000 hz.
(Certain sound management software cheerfully ignores the headers.)
Similarly, most Mac sound files are in unsigned byte format with
a sample rate of 11025 or 22050 hz.
.TP 10
.B .auto
This is a ``meta-type'': specifying this type for an input file
triggers some code that tries to guess the real type by looking for
magic words in the header.  If the type can't be guessed, the program
exits with an error message.  The input must be a plain file, not a
pipe.  This type can't be used for output files.
.SH EFFECTS
Only one effect from the palette may be applied to a sound sample.
To do multiple effects you'll need to run 
.I sox 
in a pipeline.
.TP 10
avg [ \fI-l\fR | \fI-r\fR ]
Reduce the number of channels by averaging the samples,
or duplicate channels to increase the number of channels.
This effect is automatically used when the number of input
channels differ from the number of output channels.  When reducing
the number of channels it is possible to manually specify the
avg effect and use the \fI-l\fR and \fI-r\fR options to select only
the left or right channel for the output instead of averaging the
two channels.
.TP 10
band \fB[ \fI-n \fB] \fIcenter \fB[ \fIwidth\fB ]
Apply a band-pass filter.
The frequency response drops logarithmically
around the
.I center
frequency.
The
.I width
gives the slope of the drop.
The frequencies at 
.I "center + width"
and
.I "center - width"
will be half of their original amplitudes.
.B Band
defaults to a mode oriented to pitched signals,
i.e. voice, singing, or instrumental music.
The 
.I -n
(for noise) option uses the alternate mode
for un-pitched signals.
.B Warning:
.I -n
introduces a power-gain of about 11dB in the filter, so beware
of output clipping.
.B Band
introduces noise in the shape of the filter,
i.e. peaking at the 
.I center
frequency and settling around it.
See \fBfilter\fR for a bandpass effect with steeper shoulders.
.TP 10
bandpass \fIfrequency bandwidth\fB
Butterworth bandpass filter. Description coming soon!
.TP 10
bandreject \fIfrequency bandwidth\fB
Butterworth bandreject filter.  Description coming soon!
.TP
chorus \fIgain-in gain-out delay decay speed depth 
.TP 10
       -s \fR| \fI-t [ \fIdelay decay speed depth -s \fR| \fI-t ... \fR]
Add a chorus to a sound sample.  Each quadtuple
delay/decay/speed/depth gives the delay in milliseconds
and the decay (relative to gain-in) with a modulation
speed in Hz using depth in milliseconds.
The modulation is either sinodial (-s) or triangular
(-t).  Gain-out is the volume of the output.
.TP
compand \fIattack1,decay1\fR[,\fIattack2,decay2\fR...]
.TP 
        \fIin-dB1,out-dB1\fR[,\fIin-dB2,out-dB2\fR...]
.TP 10
        [\fIgain\fR] [\fIinitial-volume\fR]
Compand (compress or expand) the dynamic range of a sample.  The
attack and decay time specify the integration time over which the
absolute value of the input signal is integrated to determine its
volume.  Where more than one pair of attack/decay parameters are
specified, each channel is treated separately and the number of pairs
must agree with the number of input channels.  The second parameter is
a list of points on the compander's transfer function specified in dB
relative to the maximum possible signal amplitude.  The input values
must be in a strictly increasing order but the transfer function does
not have to be monotonically rising.  The special value \fI-inf\fR may
be used to indicate that the input volume should be associated output
volume.  The points \fI-inf,-inf\fR and \fI0,0\fR are assumed; the
latter may be overridden, but the former may not.  The third
(optional) parameter is a postprocessing gain in dB which is applied
after the compression has taken place; the fourth (optional) parameter
is an initial volume to be assumed for each channel when the effect
starts.  This permits the user to supply a nominal level initially, so
that, for example, a very large gain is not applied to initial signal
levels before the companding action has begun to operate: it is quite
probable that in such an event, the output would be severely clipped
while the compander gain properly adjusts itself.
.TP 10
copy
Copy the input file to the output file.
This is the default effect if both files have the same 
sampling rate.
.TP 10
cut \fIloopnumber
Extract loop #N from a sample.
.TP 10
deemph
Apply a treble attenuation shelving filter to samples in
audio cd format.  The frequency response of pre-emphasized
recordings is rectified.  The filtering is defined in the
standard document ISO 908.
.TP 10
echo \fIgain-in gain-out delay decay \fR[ \fIdelay decay ... \fR]
Add echoing to a sound sample.
Each delay/decay part gives the delay in milliseconds 
and the decay (relative to gain-in) of that echo.
Gain-out is the volume of the output.
.TP 10
echos \fIgain-in gain-out delay decay \fR[ \fIdelay decay ... \fR]
Add a sequence of echos to a sound sample.
Each delay/decay part gives the delay in milliseconds 
and the decay (relative to gain-in) of that echo.
Gain-out is the volume of the output.
.TP 10
filter [ \fIlow\fR ]-[ \fIhigh\fR ] [ \fIwindow-len\fR [ \fIbeta\fR ] ]
Apply a Sinc-windowed lowpass, highpass, or bandpass filter of given
window length to the signal.
\fIlow\fR refers to the frequency of the lower 6dB corner of the filter.
\fIhigh\fR refers to the frequency of the upper 6dB corner of the filter.

A lowpass filter is obtained by leaving \fIlow\fR unspecified, or 0.
A highpass filter is obtained by leaving \fIhigh\fR unspecified, or 0,
or greater than or equal to the Nyquist frequency.

The \fIwindow-len\fR, if unspecified, defaults to 128.
Longer windows give a sharper cutoff, smaller windows a more gradual cutoff.

The \fIbeta\fR, if unspecified, defaults to 16.  This selects a Kaiser window.
You can select a Nuttall window by specifying anything <= 2.0 here.
For more discussion of beta, look under the \fBresample\fR effect.

.TP 10
flanger \fIgain-in gain-out delay decay speed -s \fR| \fI-t
Add a flanger to a sound sample.  Each triple
delay/decay/speed gives the delay in milliseconds
and the decay (relative to gain-in) with a modulation
speed in Hz.
The modulation is either sinodial (-s) or triangular
(-t).  Gain-out is the volume of the output.
.TP 10
highp \fIcenter
Apply a high-pass filter.
The frequency response drops logarithmically with 
.I center
frequency in the middle of the drop.
The slope of the filter is quite gentle.
See \fBfilter\fR for a highpass effect with sharper cutoff.
.TP 10
highpass \fIfrequency\fB
Butterworth highpass filter.  Description comming soon!
.TP 10
lowp \fIcenter
Apply a low-pass filter.
The frequency response drops logarithmically with 
.I center
frequency in the middle of the drop.
The slope of the filter is quite gentle.
See \fBfilter\fR for a lowpass effect with sharper cutoff.
.TP 10
lowpass \fIfrequency\fB
Butterworth lowpass filter.  Description coming soon!
.TP 10
map 
Display a list of loops in a sample,
and miscellaneous loop info.
.TP 10
mask
Add "masking noise" to signal.
This effect deliberately adds white noise to a sound 
in order to mask quantization effects,
created by the process of playing a sound digitally.
It tends to mask buzzing voices, for example.
It adds 1/2 bit of noise to the sound file at the
output bit depth.
.TP 10
pan \fIdirection\fB
Pan the sound of an audio file from one channel to another.  This is done by
changing the volume of the input channels so that it fade's out on one
channel and fades-in on another.  If the number of input channels is
different then the number of output channels then this effect tries to
intellegently handle this.  For instance, if the input contains 1 channel
and the output contains 2 channels, then it will create the missing channel
itself.  The 
.I direction
is a value from -1.0 to 1.0.  -1.0 represents
far left and 1.0 represents far right.  Numbers in between will start the
pan effect without totally muting the opposite channel.
.TP 10
phaser \fIgain-in gain-out delay decay speed -s \fR| \fI-t
Add a phaser to a sound sample.  Each triple
delay/decay/speed gives the delay in milliseconds
and the decay (relative to gain-in) with a modulation
speed in Hz.
The modulation is either sinodial (-s) or triangular
(-t).  The decay should be less than 0.5 to avoid
feedback.  Gain-out is the volume of the output.
.TP 10
pick
Select the left or right channel of a stereo sample,
or one of four channels in a quadrophonic sample.
.TP
polyphase [ \fI-w \fR< \fInut\fR / \fIham\fR > ] 
.TP
          [ \fI -width \fR< \fI long \fR / \fIshort \fR / \fI# \fR> ] 
.TP 10
          [ \fI-cutoff # \fR ]
Translate input sampling rate to output sampling rate via polyphase
interpolation, a DSP algorithm.  This method is slow and uses lots
of RAM, but gives much better results than 
.B rate.
.br
-w < nut / ham > : select either a Nuttal (~90 dB stopband) or Hamming
(~43 dB stopband) window.  Default is
.I nut.
.br
-width long / short / # : specify the (approximate) width of the filter.
.I long
is 1024 samples;
.I short
is 128 samples.  Alternatively, an exact number can be used.  Default is
.I long.
The
.I short
option is
.B not
recommended, as it produces poor quality results.
.br
-cutoff # : specify the filter cutoff frequency in terms of fraction of
bandwidth.  If upsampling, then this is the fraction of the original signal
that should go through.  If downsampling, this is the fraction of the
signal left after downsampling.  Default is 0.95.  Remember that
this is a float.

.TP 10
rate
Translate input sampling rate to output sampling rate
via linear interpolation to the Least Common Multiple
of the two sampling rates.
This is the default effect 
if the two files have different sampling rates and the preview options
was specified.
This is fast but noisy:
the spectrum of the original sound will be shifted upwards
and duplicated faintly when up-translating by a multiple.
Lerp-ing is acceptable for cheap 8-bit sound hardware,
but for CD-quality sound you should instead use either
.B resample
or
.B polyphase.
If you are wondering which of
.B SoX's
rate changing effects to use, you will want to read a
detailed analysis of all of them at http://eakaw2.et.tu-dresden.de/~wilde/resample/resample.html
[Nov,1999: These tests need to be updated for sox-12.17, which has bugfixes to the
resample and polyphase code.]
.TP 10
resample [ \fI-qs\fB | \fI-q\fB | \fI-ql\fB ] [ \fIrolloff\fB [ \fIbeta\fB ] ]\fR
Translate input sampling rate to output sampling rate
via simulated analog filtration.
This method is slower than 
.B rate,
but gives much better results.

The \fI-qs\fR, \fI-q\fR, or \fI-ql\fR options specify increased accuracy
at the cost of lower execution speed.  By default, linear interpolation
is used, with a window width about 45 samples at the lower rate.
This gives an accuracy of about 16 bits, but insufficient stopband rejection
in the case that you want to have rolloff greater than about 0.80 of
the Nyquist frequency.
The \fI-q*\fR options use quadratic interpolation of filter
coefficients, resulting in about 24 bits precision.
.br
Following is a table of the reasonable defaults which are built-in to sox:
.br 
   \fBOption  Window rolloff beta interpolation\fR
.br 
   \fB------  ------ ------- ---- -------------\fR
.br
   (none)    45    0.80    16     linear
.br
     -qs     45    0.80    16    quadratic
.br
     -q      75    0.875   16    quadratic
.br
     -ql    149    0.94    16    quadratic
.br 
   \fB------  ------ ------- ---- -------------\fR
.br
.br
\fI-qs\fR, \fI-q\fR, or \fI-ql\fR use window lengths of 45, 75, or 149
samples, respectively, at the lower sample-rate of the two files.
This means progressively sharper stop-band rejection, at proportionally
slower execution times.

\fIrolloff\fR refers to the cut-off frequency of the
low pass filter and is given in terms of the
Nyquist frequency for the lower sample rate.  rolloff therefore should
be something between 0. and 1., in practice 0.8-0.95.  The defaults are
indicated above.

The \fIbeta\fR parameter
determines the type of filter window used.  Any value greater than 2.0 is
the beta for a Kaiser window.  Beta <= 2.0 selects a Nuttall window.
If unspecified, the default is a Kaiser window with beta 16.

In the case of Kaiser window (beta > 2.0), lower betas produce a somewhat
faster transition from passband to stopband, at the cost of noticeable artifacts.
A beta of 16 is the default, beta less than 10 is not recommended.  If you want
a sharper cutoff, don't use low beta's, use a longer sample window.
A Nuttall window is selected by specifying any 'beta' <= 2, and the
Nuttall window has somewhat steeper cutoff than the default Kaiser window.
You will probably not need to use the beta parameter at all, unless you are
just curious about comparing the effects of Nuttall vs. Kaiser windows.

This is the default effect if the two files have different sampling rates.
Default parameters are, as indicated above, Kaiser window of length 45,
rolloff 0.80, beta 16, linear interpolation.

\fBNOTE: \fI-qs\fR is only slightly slower, but more accurate for
16-bit or higher precision.

\fBNOTE:\fR In many cases of up-sampling, no interpolation is needed,
as exact filter coefficients can be computed in a reasonable amount of space.
To be precise, this is done when

.br
           input_rate < output_rate
.br
                      &&
.br
  output_rate/gcd(input_rate,output_rate) <= 511
.br
.TP 10
reverb \fIgain-out delay \fR[ \fIdelay ... \fR]
Add reverberation to a sound sample.  Each delay is given 
in milliseconds and its feedback is depending on the
reverb-time in milliseconds.  Each delay should be in 
the range of half to quarter of reverb-time to get
a realistic reverberation.  Gain-out is the volume of the
output.
.TP 10
reverse 
Reverse the sound sample completely.
Included for finding Satanic subliminals.
.TP 10
speed \ffactor\f
Speed up or down the sound, as a magnetic tape with a speed control. 
It affects both pitch and time. A factor of 1.0 means no change, 
and is the default. 
2.0 doubles speed, thus time length is cut by a half and pitch 
is one octave higher. 
0.5 halves speed thus time length doubles and pitch is one octave lower. 
.TP 10
split
Turn a mono sample into a stereo sample by copying
the input channel to the left and right channels.
.TP 10
stat [ debug | -v ]
Do a statistical check on the input file,
and print results on the standard error file.
.B stat
may copy the file untouched from input to output,
if you select an output file.  
The "Volume Adjustment:" field in the statistics
gives you the argument to the
.B -v
.I number
which will make the sample as loud as possible without clipping. 
There is an optional parameter
.B -v
that will print out the "Volume Adjustment:" field's value and
return.  This could be of use in scripts to auto convert the
volume.  There is an also an optional parameter
.B debug
that will place sox into debug mode and print out a hex dump of the
sound file from the internal buffer that is in 32-bit signed PCM data.
This is mainly only of use in tracking down endian problems that
creep in to sox on cross-platform versions.
.TP 10
swap [ \fI1 2 3 4\fB ]
Swap channels in multi-channel sound files.  In files with more than 2
channels you may specify the order that the channels should be rearranged
in.
.TP 10
vibro \fIspeed \fB [ \fIdepth\fB ]
Add the world-famous Fender Vibro-Champ sound
effect to a sound sample by using
a sine wave as the volume knob.
.B Speed 
gives the Hertz value of the wave.
This must be under 30.
.B Depth
gives the amount the volume is cut into
by the sine wave,
ranging 0.0 to 1.0 and defaulting to 0.5.
.TP 10
vol \fIgain \fB [ \fItype\fB ]
The vol effect is much like the command line option -v.  It allows you to
adjust the volume of an input file and allows you to specify the adjustment
in relation to amplitude, power, or dB.  When type is 
.I amplitude
then a linear change of the amplitude is performed based on the gain.  Therefore,
a value of 1.0 will keep the volume the same, 0.0 to < 1.0 will cause the
volume to decrease and values of > 1.0 will cause the volume to increase.
Beware of clipping audio data when the gain is greater then 1.0.  A negative
value performs the same adjustment while also changing the phase.
.br
When type is 
.I power
then a value of 1.0 also means no change in volume.
.br
When type is 
.I dB
the amplitude is change logarithmically.
0.0 is constant while +6 doubles the amplitude.
.P
.I Sox
enforces certain effects.
If the two files have different sampling
rates, the requested effect must be one of
.B copy,
or
.B rate,
." or
." .B resample.
If the two files have different numbers of channels,
the 
.B avg
." or other channel mixing
effect must be requested.
.SH BUGS
The syntax is horrific.  Thats the breaks when trying to handle all things from the command line.
.P
Please report any bugs found in this version of sox to Chris Bagwell (cbagwell@sprynet.com)
.SH FILES
.SH SEE ALSO
.BR play (1),
.BR rec (1),
.BR soxexam(1)
.SH NOTICES
The version of Sox that accompanies this manual page is support by 
Chris Bagwell (cbagwell@sprynet.com).  Please refer any questions 
regarding it to this address.  You may obtain the latest version at the 
the web site http://home.sprynet.com/~cbagwell/sox.html
