'\" t
'\" The line above instructs most `man' programs to invoke tbl
'\"
'\" Separate paragraphs; not the same as PP which resets indent level.
.de SP
.if t .sp .5
.if n .sp
..
'\"
'\" Replacement em-dash for nroff (default is too short).
.ie n .ds m " - 
.el .ds m \(em
'\"
'\" Placeholder macro for if longer nroff arrow is needed.
.ds RA \(->
'\"
'\" Decimal point set slightly raised
.ds d \v'-.15m'.\v'+.15m'
'\"
.TH SoX 7 "January 31, 2007" "soxlua" "Sound eXchange"
.SH NAME
soxlua\*mLua scripting of SoX
.SH DESCRIPTION
This man page explains how to write SoX effects and file formats in
Lua. For documentation of Lua, see http://www.lua.org/; SoX currently
uses Lua 5.1, whose manual can be found at
http://www.lua.org/manual/5.1/manual.html. For details of the workings
of SoX effects and formats, see
.BR libst (3) .
The Lua programming interface is very similar to that for C.
.SH GENERAL
SoX embeds a Lua interpreter with all the standard libraries
available. This might change in future to make SoX more secure; in
particular, format and effects scripts intended to be future-proof
should not use the os library, and only use the io library on file
handles supplied by SoX.
.SP
SoX adds support to Lua for arrays of st_sample_t. These arrays can be
used like normal Lua tables, but are of fixed size. As normal in Lua,
they are one-based, that is, the valid incides for an array `a' are
from 1 to #a inclusive.
.SH EFFECTS
To be written.
.SH FORMATS
To be written.
.SH SEE ALSO
.BR sox (1),
.BR libst (3)
.SH AUTHORS
This man page was written by Reuben Thomas (rrt@sc3d.org).
