/* FIXME: generate this list automatically */

  EFFECT(allpass)
  EFFECT(avg)
  EFFECT(band)
  EFFECT(bandpass)
  EFFECT(bandreject)
  EFFECT(bass)
  EFFECT(chorus)
  EFFECT(compand)
  EFFECT(dcshift)
  EFFECT(deemph)
  EFFECT(dither)
  EFFECT(earwax)
  EFFECT(echo)
  EFFECT(echos)
  EFFECT(equalizer)
  EFFECT(fade)
  EFFECT(filter)
  EFFECT(flanger)
  EFFECT(highpass)
  EFFECT(highp)
#ifdef HAVE_LIBSOUNDTOUCH
  EFFECT(key)
#endif
#ifdef HAVE_LADSPA_H
  EFFECT(ladspa)
#endif
  EFFECT(lowpass)
  EFFECT(lowp)
  EFFECT(mask)
  EFFECT(mcompand)
  EFFECT(mixer)
  EFFECT(noiseprof)
  EFFECT(noisered)
  EFFECT(oops)
  EFFECT(pad)
  EFFECT(pan)
  EFFECT(phaser)
  EFFECT(pick)
  EFFECT(pitch)
  EFFECT(polyphase)
#ifdef HAVE_SAMPLERATE_H
  EFFECT(rabbit)
#endif
  EFFECT(rate)
  EFFECT(repeat)
  EFFECT(resample)
  EFFECT(reverb)
  EFFECT(reverse)
  EFFECT(silence)
  EFFECT(speed)
  EFFECT(stat)
  EFFECT(stretch)
  EFFECT(swap)
  EFFECT(synth)
#ifdef HAVE_LIBSOUNDTOUCH
  EFFECT(tempo)
#endif
  EFFECT(treble)
  EFFECT(tremolo)
  EFFECT(trim)
  EFFECT(vibro)
  EFFECT(vol)
