#define PACKAGE_VERSION "14.4.1"

#cmakedefine EXTERNAL_GSM             1
#cmakedefine EXTERNAL_LPC10           1
#cmakedefine HAVE_ALSA                1
#cmakedefine HAVE_AMRNB               1
#cmakedefine HAVE_AMRWB               1
#cmakedefine HAVE_AO                  1
#cmakedefine HAVE_BYTESWAP_H          1
#cmakedefine HAVE_COREAUDIO           1
#cmakedefine HAVE_FFMPEG              1
#cmakedefine HAVE_FLAC                1
#cmakedefine HAVE_FMEMOPEN            1
#cmakedefine HAVE_FSEEKO              1
#cmakedefine HAVE_GETTIMEOFDAY        1
#cmakedefine HAVE_GLOB_H              1
#define HAVE_GSM                      1
#cmakedefine HAVE_ID3TAG              1
#cmakedefine HAVE_ID3TAG_SET_FIELDVALUE 1
#cmakedefine HAVE_INTTYPES_H          1
#cmakedefine HAVE_IO_H                1
#cmakedefine HAVE_LAME_LAME_H         1
#cmakedefine HAVE_LAME_SET_VBR_QUALITY 1
#define HAVE_LPC10                    1
#cmakedefine HAVE_LTDL_H              1
#cmakedefine HAVE_MACHINE_SOUNDCARD_H 1
#cmakedefine HAVE_MAD_H               1
#cmakedefine HAVE_MAGIC               1
#cmakedefine HAVE_MKSTEMP             1
#cmakedefine HAVE_MP3                 1
#cmakedefine HAVE_OGG_SPEEX           1
#cmakedefine HAVE_OGG_VORBIS          1
#cmakedefine HAVE_OPENMP              1
#cmakedefine HAVE_OSS                 1
#cmakedefine HAVE_PNG                 1
#cmakedefine HAVE_POPEN               1
#cmakedefine HAVE_PULSEAUDIO          1
#cmakedefine HAVE_SNDFILE             1
#cmakedefine HAVE_SNDFILE_1_0_18      1
#cmakedefine HAVE_SNDIO               1
#cmakedefine HAVE_STDINT_H            1
#cmakedefine HAVE_STRCASECMP          1
#cmakedefine HAVE_STRING_H            1
#cmakedefine HAVE_STRINGS_H           1
#cmakedefine HAVE_STRRSTR             1
#cmakedefine HAVE_SUN_AUDIO           1
#cmakedefine HAVE_SUN_AUDIOIO_H       1
#cmakedefine HAVE_SYS_AUDIOIO_H       1
#cmakedefine HAVE_SYS_SOUNDCARD_H     1
#cmakedefine HAVE_SYS_STAT_H          1
#cmakedefine HAVE_SYS_TIMEB_H         1
#cmakedefine HAVE_SYS_TIME_H          1
#cmakedefine HAVE_SYS_TYPES_H         1
#cmakedefine HAVE_SYS_UTSNAME_H       1
#cmakedefine HAVE_TERMIOS_H           1
#cmakedefine HAVE_UNISTD_H            1
#cmakedefine HAVE_VSNPRINTF           1
#cmakedefine HAVE_WAVPACK             1
#cmakedefine WORDS_BIGENDIAN          1
